### ISSUE TITLE
Adding more certificate template

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#1]
Currently, there is only one certificate template in which the certificate is generated. add more to make it more usable.

**Task**

- make new certificate templates
-  make sure the annotation on the certificate works as well

**Comment by GundaSudarrshan** [comment]
I am Interested to work on this please assign this to me
and I have few questions regarding the template of certificate like
what title it should have? ( appreciation or participation)
should it have name etc.. and more

**Comment by HeyAnirudh** [comment]
> I am Interested to work on this please assign this to me and I have few questions regarding the template of certificate like what title it should have? ( appreciation or participation) should it have name etc.. and more



> I am Interested to work on this please assign this to me and I have a few questions regarding the template of the certificate like what title it should have? ( appreciation or participation) should it have a name etc.. and more

it can be of any type appreciation or winner etc. (use your creativity) and the name part should be blank, there user needs to their name in it.

**Comment by GundaSudarrshan** [comment]
Hey @HeyAnirudh  I have Created a Pull Request regarding this Issue, Can You please Check

**Comment by deepshikha2708** [comment]
Can you please assign me this issue?

**Comment by HeyAnirudh** [comment]
> Hey @HeyAnirudh I have Created a Pull Request regarding this Issue, Can You please Check

hey @GundaSudarrshan thank you for the pr . i will check it soon. till then feel free to explore the project and search easy to enhance it :)

**Comment by deepshikha2708** [comment]
can I also work on this issue?

**Comment by HeyAnirudh** [comment]
> can I also work on this issue?

yes , want me to assign it to you ?

**Comment by deepshikha2708** [comment]
> > can I also work on this issue?
> 
> yes , want me to assign it to you ?

yes please

**Comment by HeyAnirudh** [comment]
> > > can I also work on this issue?
> > 
> > 
> > yes , want me to assign it to you ?
> 
> yes please

assigned! you have 3 days!

**Comment by deepshikha2708** [comment]
@HeyAnirudh  I have the template ready but I have doubt in uploading the png file.

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh I have the template ready but I have doubt in uploading the png file.

yeah whats the doubt?

**Comment by deepshikha2708** [comment]
as in how to attach the png file

**Comment by GundaSudarrshan** [comment]
@deepshikha2708  you can Just add the image inside the Templates folder and then then follow remaining process as usual
git add .
git commit -m "your-message:
git push

**Comment by deepshikha2708** [comment]
actually I am not able to upload the png file int the templates folder.

**Comment by HeyAnirudh** [comment]
> actually I am not able to upload the png file int the templates folder.

@deepshikha2708  why so? what is it showing?

**Comment by deepshikha2708** [comment]
Do I just need to paste the image right? or do something else?

**Comment by HeyAnirudh** [comment]
@deepshikha2708  yes just paste it
