### ISSUE TITLE
Add certificate output in readme

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#15]
This is a very basic issue, run the app and show step by step procedure and add it in readme with proper images

it can also be a video of a walkthrough of generating a certificate ...use your creativity!!

**Comment by Rakesh9100** [comment]
> This is a very basic issue, run the app and show step by step procedure and add it in readme with proper images
> 
> it can also be a video of a walkthrough of generating a certificate ...use your creativity!!

I would like to work on this kindly assign.

**Comment by debjit20504** [comment]
> This is a very basic issue, run the app and show step by step procedure and add it in readme with proper images
> 
> it can also be a video of a walkthrough of generating a certificate ...use your creativity!!

Done :)

**Comment by HeyAnirudh** [comment]
> > This is a very basic issue, run the app and show step by step procedure and add it in readme with proper images
> > it can also be a video of a walkthrough of generating a certificate ...use your creativity!!
> 
> Done :)
 
did you ask me to assign this issue to you?

**Comment by debjit20504** [comment]
@HeyAnirudh No, but you haven't specified in your Contributing section that we should ask you about assigning the issue. I just followed the Instruction that you have given in Contribute Section.

**Comment by Rakesh9100** [comment]
Should I work on this or not ? Its assigned to me or will unassign and assign again ?

**Comment by GundaSudarrshan** [comment]
@HeyAnirudh  Pls Assign me this Issue

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh No, but you haven't specified in your Contributing section that we should ask you about assigning the issue. I just followed the Instruction that you have given in Contribute Section.

brother that a general contributing , now as a hsoc participant you need to follow their rules.

**Comment by debjit20504** [comment]
> > @HeyAnirudh No, but you haven't specified in your Contributing section that we should ask you about assigning the issue. I just followed the Instruction that you have given in Contribute Section.
> 
> brother that a general contributing , now as a hsoc participant you need to follow their rules.

Sorry, I'll take care next time.

**Comment by Rakesh9100** [comment]
Why did you unassign me ? Kindly assign @debjit20504 @HeyAnirudh 
Should I work on this or not ?

**Comment by debjit20504** [comment]
> Why did you unassign me ? Kindly assign @debjit20504 @HeyAnirudh Should I work on this or not ?

@Rakesh9100 are bro, this is their HSOC project, and only those who are HSOC participant who have take this project can contribute and should be bcoz they are the one's who are assigned to do this project we are not HSOC participants so we should stay out of this.. :)

**Comment by Rakesh9100** [comment]
> > Why did you unassign me ? Kindly assign @debjit20504 @HeyAnirudh Should I work on this or not ?
> 
> @Rakesh9100 are bro, this is their HSOC project, and only those who are HSOC participant who have take this project can contribute and should be bcoz they are the one's who are assigned to do this project we are not HSOC participants so should stay out of this.. :)

I am HSOC participant and so asking to assign.

**Comment by debjit20504** [comment]
> > > Why did you unassign me ? Kindly assign @debjit20504 @HeyAnirudh Should I work on this or not ?
> > 
> > 
> > @Rakesh9100 are bro, this is their HSOC project, and only those who are HSOC participant who have take this project can contribute and should be bcoz they are the one's who are assigned to do this project we are not HSOC participants so should stay out of this.. :)
> 
> I am HSOC participant and so asking to assign.

ohh then Good luck bro 👍

**Comment by Rakesh9100** [comment]
No, leave it now and assign to others to those who need this issue to work.

**Comment by HeyAnirudh** [comment]
hey @debjit20504, I didn't know you weren't a part of hsoc22. you are welcomed to contribute in this project.  i will look into your pr and currently assign @Rakesh9100 in this.

**Comment by HeyAnirudh** [comment]
Update everyone!! @debjit20504 has already done with video walkthrough will be soon merging it . other people can work on image walktrough .  (new suggestions are appreciated)

**Comment by HeyAnirudh** [comment]
@Rakesh9100 you have been assigned, you got 2 days to complete it.

**Comment by HeyAnirudh** [comment]
@Rakesh9100 any update?

**Comment by Rakesh9100** [comment]
> @Rakesh9100 any update?

Assign to the other contributor.

**Comment by debjit20504** [comment]
> > @Rakesh9100 any update?
> 
> Assign to the other contributor.

What's the issue ?

**Comment by Rakesh9100** [comment]
What to do in this now since it's already done by you in a form of Video. @debjit20504 . So owner can merge that video with this issue and close this.

**Comment by debjit20504** [comment]
Yeah that's what I'm thinking that why isn't this closed yet..
