### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#19]
its showing the below image instead of the  certificate template 
![image](https://user-images.githubusercontent.com/64551845/184544956-793cd401-225d-414c-8074-a6e7c5ae6e13.png)

**Comment by GundaSudarrshan** [comment]
@HeyAnirudh  assign me this issue 
I will resolve this one

**Comment by HeyAnirudh** [comment]
assigned!

**Comment by GundaSudarrshan** [comment]
![image](https://user-images.githubusercontent.com/70209862/184589270-4d16affc-a899-4991-bc7e-1a2819f054cb.png)

I have **resolved the Issue** Updating the **BUG** Branch please check PR

**Comment by HeyAnirudh** [comment]
Solved by @GundaSudarrshan
