### ISSUE TITLE
improve Readme.md

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#2]
Edit the readme file. add more information regarding the project according to your understanding.

**Comment by afreenabegum** [comment]
Please assign it to me !!
But contribution will start from July 15, right?

**Comment by HeyAnirudh** [comment]
> Please assign it to me !! But contribution will start from July 15, right?

yeah it does starts from  15th, so you can start adding  up pull requests on 15th

**Comment by afreenabegum** [comment]
Okay !! Thank you.

**Comment by Soumya-Kushwaha** [comment]
I want to work on this issue

**Comment by deepshikha2708** [comment]
I want to work on this issue

**Comment by HeyAnirudh** [comment]
@afreenabegum  do you still want to work on this issue or shall I assign it to others?

**Comment by afreenabegum** [comment]
Assign it to others.. Am not aware of python. So, I removed by assignment.

**Comment by HeyAnirudh** [comment]
> I want to work on this issue

hey @deepshikha2708 , i just saw you created a PR , note that without getting assigned into the issue you cant randomly create pr's.  next time do inform me  :)

**Comment by HeyAnirudh** [comment]
Guys this issue will always be open for all!!

**Comment by HeyAnirudh** [comment]
> Assign it to others.. Am not aware of python. So, I removed by assignment.

alright :)

**Comment by HeyAnirudh** [comment]
@deepshikha2708 and @Soumya-Kushwaha  you both are assigned to it as @deepshikha2708 already created a pr ill look into it where are @Soumya-Kushwaha you have 2 days to create a pr.

**Comment by HeyAnirudh** [comment]
@deepshikha2708  is there any update?

**Comment by HeyAnirudh** [comment]
@Soumya-Kushwaha is there any update?

**Comment by Soumya-Kushwaha** [comment]
@HeyAnirudh I was sick since last 2 days. I'll update it now asap, if you can extend deadline by 1-2 days. Elsewhise close the issue!

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh I was sick since last 2 days. I'll update it now asap, if you can extend deadline by 1-2 days. Elsewhise close the issue!

its okay ,hope you are doing well now. 
take one more day to complete
