### ISSUE TITLE
Center the logo in the side bar 

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#21]
The logo in the sidebar needs to be in the center 

for your reference 
![image](https://user-images.githubusercontent.com/64551845/184545109-34728b35-aab0-4473-92b2-c44b368414f7.png)

**Comment by GundaSudarrshan** [comment]
@HeyAnirudh  pls assign me this issue

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh pls assign me this issue

I would recommend you to work on one issue at a time, since this issue is small will assign you.

**Comment by HeyAnirudh** [comment]
Completed by @GundaSudarrshan
