### ISSUE TITLE
Font of text

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#3]
adding new fonts in the text. you could explore OpenCV fonts etc.

**Comment by Beatrix-droid** [comment]
could you assign this to me please?

**Comment by HeyAnirudh** [comment]
> 

Assigned!

**Comment by HeyAnirudh** [comment]
> could you assign this to me please?

done!

**Comment by Beatrix-droid** [comment]
> > could you assign this to me please?
> 
> done!

Thank you! I was about to start working on it but before that I noticed that there was a problem with running the app:
My computer is running Linux, and as such, when it tries to run the app, it does not find the hard coded values:
``'C:\\Users\\Admin\Desktop\\github\\certificates_streamlit\\pics\\apricus.png')``
and 
``"images\\img.png")``

because the way linux organises the file system is a bit different (ie there is no C drive for example).

Before I try and fixing the fonts issue, may I open a separate Pull Request and try changing these hardcoded values using the python OS module,  abstracting these hard coded values so that the app runs on Mac OS, Linux,and windows with no problems?

**Comment by HeyAnirudh** [comment]
yes

> > > could you assign this to me please?
> > 
> > 
> > done!
> 
> Thank you! I was about to start working on it but before that I noticed that there was a problem with running the app: My computer is running Linux, and as such, when it tries to run the app, it does not find the hard coded values: `'C:\\Users\\Admin\Desktop\\github\\certificates_streamlit\\pics\\apricus.png')` and `"images\\img.png")`
> 
> because the way linux organises the file system is a bit different (ie there is no C drive for example).
> 
> Before I try and fixing the fonts issue, may I open a separate Pull Request and try changing these hardcoded values using the python OS module, abstracting these hard coded values so that the app runs on Mac OS, Linux,and windows with no problems?

thank you @Beatrix-droid  for pointing out the issue, and yes could you open a pull request but not before the 15th.

**Comment by Beatrix-droid** [comment]
> yes
> 
> > > > could you assign this to me please?
> > > 
> > > 
> > > done!
> > 
> > 
> > Thank you! I was about to start working on it but before that I noticed that there was a problem with running the app: My computer is running Linux, and as such, when it tries to run the app, it does not find the hard coded values: `'C:\\Users\\Admin\Desktop\\github\\certificates_streamlit\\pics\\apricus.png')` and `"images\\img.png")`
> > because the way linux organises the file system is a bit different (ie there is no C drive for example).
> > Before I try and fixing the fonts issue, may I open a separate Pull Request and try changing these hardcoded values using the python OS module, abstracting these hard coded values so that the app runs on Mac OS, Linux,and windows with no problems?
> 
> thank you @Beatrix-droid for pointing out the issue, and yes could you open a pull request but not before the 15th.

My apologies, I had some spare time this morning, and unfortunately have already fixed the issue and created a PR. This was before you replied to me.
If you'd like you can close the PR, and I can make another identical PR on the 15th :)

**Comment by HeyAnirudh** [comment]
> > yes
> > > > > could you assign this to me please?
> > > > 
> > > > 
> > > > done!
> > > 
> > > 
> > > Thank you! I was about to start working on it but before that I noticed that there was a problem with running the app: My computer is running Linux, and as such, when it tries to run the app, it does not find the hard coded values: `'C:\\Users\\Admin\Desktop\\github\\certificates_streamlit\\pics\\apricus.png')` and `"images\\img.png")`
> > > because the way linux organises the file system is a bit different (ie there is no C drive for example).
> > > Before I try and fixing the fonts issue, may I open a separate Pull Request and try changing these hardcoded values using the python OS module, abstracting these hard coded values so that the app runs on Mac OS, Linux,and windows with no problems?
> > 
> > 
> > thank you @Beatrix-droid for pointing out the issue, and yes could you open a pull request but not before the 15th.
> 
> My apologies, I had some spare time this morning, and unfortunately have already fixed the issue and created a PR. This was before you replied to me. If you'd like you can close the PR, and I can make another identical PR on the 15th :)



> > yes
> > > > > could you assign this to me please?
> > > > 
> > > > 
> > > > done!
> > > 
> > > 
> > > Thank you! I was about to start working on it but before that I noticed that there was a problem with running the app: My computer is running Linux, and as such, when it tries to run the app, it does not find the hard coded values: `'C:\\Users\\Admin\Desktop\\github\\certificates_streamlit\\pics\\apricus.png')` and `"images\\img.png")`
> > > because the way linux organises the file system is a bit different (ie there is no C drive for example).
> > > Before I try and fixing the fonts issue, may I open a separate Pull Request and try changing these hardcoded values using the python OS module, abstracting these hard coded values so that the app runs on Mac OS, Linux,and windows with no problems?
> > 
> > 
> > thank you @Beatrix-droid for pointing out the issue, and yes could you open a pull request but not before the 15th.
> 
> My apologies, I had some spare time this morning, and unfortunately have already fixed the issue and created a PR. This was before you replied to me. If you'd like you can close the PR, and I can make another identical PR on the 15th :)

hey instead delete the pr and make this an issue and self-appoint it, it would be even better.  ill share the format of creating a issue in the discord soon.
