### ISSUE TITLE
Certificate options

### ISSUE THREAD

**Issue by HeyAnirudh** [HeyAnirudh/Certificate-Generator#9]
currently, we are working with one certificate at a time, to choose another certificate we change the code, let's reduce this user dependency by creating an option on the screen to choose the certificate.

Task-

1) make a range of options for certificates.
2) you could add certificate options on the sidebar or the main screen.

this is the cheatsheet of streamlit - [streamlit](https://docs.streamlit.io/library/cheatsheet)

**Comment by GundaSudarrshan** [comment]
@HeyAnirudh  can you assign me this Issue

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh can you assign me this Issue

assigned! best of luck!

**Comment by deepshikha2708** [comment]
can you assign this issue to me too?

**Comment by HeyAnirudh** [comment]
> @HeyAnirudh can you assign me this Issue

You got 3 days solve this issue

**Comment by HeyAnirudh** [comment]
> can you assign this issue to me too?

As of now it's already taken, you can still create your own issues .
